// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlwyvohvpwrcqczqdwtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsd3l2b2h2cHdyY3FjenFkd3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTQ3NjAsImV4cCI6MjA2NTk5MDc2MH0.rJ7Xjbzmp65UITEviLlLSktqz9bBuh8JPpqVeehqXLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});